# Generated by Django 2.2.15 on 2021-07-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments_app', '0003_auto_20210722_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='title',
        ),
    ]
